'use client';

import { useActionState } from 'react';
import { closeCashSessionAction, createCashMovementAction, openCashSessionAction, type CashActionState } from '@/app/actions/cash';
import { SubmitButton } from '@/components/form-status';

export function OpenCashForm() { const [state, action] = useActionState<CashActionState, FormData>(openCashSessionAction, {}); return <form action={action} className="space-y-4 rounded-2xl border bg-white p-6 shadow-sm"><label className="block text-sm font-semibold">Monto inicial<input className="mt-1 w-full rounded-lg border px-3 py-2" min="0" name="opening_amount" required step="0.01" type="number" /></label><label className="block text-sm font-semibold">Notas<textarea className="mt-1 w-full rounded-lg border px-3 py-2" name="notes" rows={3} /></label><SubmitButton label="Abrir caja" />{state.error ? <p className="text-sm font-semibold text-red-700">{state.error}</p> : null}</form>; }
export function CashMovementForm() { const [state, action] = useActionState<CashActionState, FormData>(createCashMovementAction, {}); return <form action={action} className="grid gap-3 rounded-2xl border bg-white p-6 shadow-sm md:grid-cols-2"><label className="text-sm font-semibold">Tipo<select className="mt-1 w-full rounded-lg border px-3 py-2" name="movement_type"><option value="cash_in">Ingreso</option><option value="cash_out">Retiro</option></select></label><label className="text-sm font-semibold">Monto<input className="mt-1 w-full rounded-lg border px-3 py-2" min="0.01" name="amount" required step="0.01" type="number" /></label><label className="text-sm font-semibold md:col-span-2">Razón<input className="mt-1 w-full rounded-lg border px-3 py-2" name="reason" required /></label><div className="md:col-span-2"><SubmitButton label="Registrar movimiento" />{state.error ? <p className="mt-2 text-sm font-semibold text-red-700">{state.error}</p> : null}{state.success ? <p className="mt-2 text-sm font-semibold text-green-800">{state.success}</p> : null}</div></form>; }
export function CloseCashForm() { const [state, action] = useActionState<CashActionState, FormData>(closeCashSessionAction, {}); return <form action={action} className="space-y-4 rounded-2xl border bg-white p-6 shadow-sm"><label className="block text-sm font-semibold">Monto contado<input className="mt-1 w-full rounded-lg border px-3 py-2" min="0" name="counted_amount" required step="0.01" type="number" /></label><label className="block text-sm font-semibold">Notas<textarea className="mt-1 w-full rounded-lg border px-3 py-2" name="notes" rows={3} /></label><SubmitButton label="Cerrar caja" />{state.error ? <p className="text-sm font-semibold text-red-700">{state.error}</p> : null}</form>; }
